version: '3.7'

#Docker Networks
networks:
  proxy:
    external: true
  internal:
    driver: bridge
    external: false

#Volumes
volumes:
  dbdata:
    driver: local

services:
  #Laravel PHP Service
  app:
    build:
      context: ${BUILD_DIR}
      dockerfile: Dockerfile
    image: "nangjogja"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.app.rule=Host(`${DOMAIN_NAME_APP}`)"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.routers.app.priority=1"
      - "traefik.http.middlewares.app.contenttype.autodetect=false"
      - "traefik.http.middlewares.app.compress=true"
      - "traefik.http.middlewares.app.ratelimit.average=300"
      - "traefik.http.middlewares.app.ratelimit.burst=500"
      - "traefik.http.services.app.loadbalancer.passhostheader=true"
      - "traefik.http.services.app.loadbalancer.responseforwarding.flushinterval=60s"
      - "traefik.http.services.app.loadbalancer.server.scheme=http"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.http.services.app.loadbalancer.healthcheck.port=80"
      - "traefik.http.services.app.loadbalancer.healthcheck.hostname=${DOMAIN_NAME_APP}"
      - "traefik.http.services.app.loadbalancer.healthcheck.timeout=5s"
      - "traefik.http.services.app.loadbalancer.healthcheck.interval=10s"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: ${WORKDIR}
    volumes:
      - "./src:/var/www"
      - "${BUILD_DIR}/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - proxy
      - internal