version: '3.7'

#Docker Networks
networks:
  proxy:
    external: true
  internal:
    driver: bridge
    external: false

#Volumes
volumes:
  dbdata:
    driver: local

services:
  #MySQL Service
  db:
    image: "mysql:5.7"
    container_name: "nangjogja-db"
    hostname: "nangjogja-db"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - "traefik.http.routers.db.rule=Host(`db.localhost`)"
      - "traefik.http.routers.db.entrypoints=mysql"
      - "traefik.http.routers.db.service=db"
      - "traefik.http.services.db.loadbalancer.server.port=3306"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - "dbdata:/var/lib/mysql/"
      - "${BUILD_DIR}/mysql/my.cnf:/etc/mysql/my.cnf"
    networks:
      - internal
