version: '3.7'

#Docker Networks
networks:
  proxy:
    external: true
  internal:
    driver: bridge
    external: false

#Volumes
volumes:
  dbdata:
    driver: local

services:
#   # Traefik Service
#   traefik:
#     image: "traefik:v2.2"
#     container_name: "traefik"
#     hostname: "traefik"
#     restart: unless-stopped
#     ports:
#       - "80:80"
#       - "8080:8080"
#     labels:
#       - "traefik.docker.network=proxy"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
#       - "./build/traefik/traefik.yml:/traefik.yml"
#       - "./build/cred/users_credentials:/users_credentials"
#       - "./log/traefik.log:/etc/traefik/traefik.log"
#       - "./log/access_traefik.log:/etc/traefik/access.log"
#     networks:
#       - proxy

  #Laravel PHP Service
  app:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: nangjogja
    container_name: nangjogja-app
    hostname: "nangjogja-app"
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=proxy"
    #   - "traefik.http.routers.app.rule=Host(`nangjogja.gloqi.com`)"
    #   - "traefik.http.routers.app.entrypoints=http"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - db
    volumes:
      - "./src:/var/www"
      - "./build/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - proxy
      - internal

  #Nginx Service
  webserver:
    image: "nginx:alpine"
    container_name: "nangjogja-webserver"
    hostname: "nangjogja-webserver"
    restart: unless-stopped
    ports:
      - "80:80"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=proxy"
    #   - "traefik.http.routers.webserver.rule=Host(`webserver.localhost`)"
    #   - "traefik.http.routers.webserver.entrypoints=http"
    volumes:
      - "./src:/var/www"
      - "./build/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./log/nginx.log:/var/log/nginx/error.log"
      - "./log/access_nginx.log:/var/log/nginx/access.log"
    # healthcheck:
    #   test: wget --quiet --tries=1 --spider http://nangjogja.gloqi.com || exit 1z
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    depends_on:
      - app
    networks:
      - proxy
      - internal

  #MySQL Service
  db:
    image: "mysql:5.7"
    container_name: "nangjogja-db"
    hostname: "nangjogja-db"
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=internal"
    #   - "traefik.http.routers.db.rule=Host(`db.localhost`)"
    #   - "traefik.http.routers.db.entrypoints=mysql"
    environment:
      MYSQL_DATABASE: nangjogja
      MYSQL_USER: nangjogja
      MYSQL_ROOT_PASSWORD: jh7ghggh
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - "dbdata:/var/lib/mysql/"
      - "./build/mysql/my.cnf:/etc/mysql/my.cnf"
    networks:
      - internal
