version: '3.7'

#Docker Networks
networks:
  proxy:
    external: true
  internal:
    driver: bridge
    external: false

#Volumes
volumes:
  dbdata:
    driver: local

services:
  #Nginx Service
  webserver:
    image: "nginx:alpine"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.webserver.rule=Host(`${DOMAIN_NAME_APP}`)"
      - "traefik.http.routers.webserver.entrypoints=http"
      - "traefik.http.routers.webserver.service=webserver"
      - "traefik.http.routers.webserver.priority=2"
      - "traefik.http.middlewares.webserver.contenttype.autodetect=false"
      - "traefik.http.middlewares.webserver.compress=true"
      - "traefik.http.middlewares.webserver.ratelimit.average=300"
      - "traefik.http.middlewares.webserver.ratelimit.burst=500"
      - "traefik.http.services.webserver.loadbalancer.passhostheader=true"
      - "traefik.http.services.webserver.loadbalancer.responseforwarding.flushinterval=60s"
      - "traefik.http.services.webserver.loadbalancer.server.scheme=http"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"
      - "traefik.http.services.webserver.loadbalancer.healthcheck.port=80"
      - "traefik.http.services.webserver.loadbalancer.healthcheck.hostname=${DOMAIN_NAME_APP}"
      - "traefik.http.services.webserver.loadbalancer.healthcheck.timeout=5s"
      - "traefik.http.services.webserver.loadbalancer.healthcheck.interval=10s"
    working_dir: ${WORKDIR}
    volumes:
      - "${LARAVEL_PROJECT_DIR}:/var/www"
      - "${BUILD_DIR}/nginx/conf.d/:/etc/nginx/conf.d/"
      - "${LOG_DIR}/nginx.log:/var/log/nginx/error.log"
      - "${LOG_DIR}/access_nginx.log:/var/log/nginx/access.log"
    networks:
      - proxy
      - internal