serversTransport:
  maxIdleConnsPerHost: 1000
  forwardingTimeouts:
    dialTimeout: 60
entryPoints:
  http:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 120
        graceTimeOut: 120
      respondingTimeouts:
        readTimeout: 120
        writeTimeout: 120
        idleTimeout: 240
  https:
    address: ":443"
  mysql:
    address: ":3306"
api:
  insecure: false
  dashboard: false
  debug: false
log:
  level: DEBUG
  filePath: "/etc/traefik/traefik.log"
  format: "json"
accessLog:
  filePath: "/etc/traefik/access.log"
  filters:
    statusCodes:
      - 400
      - 499
      - 500
providers:
  providersThrottleDuration: 2
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    swarmMode: true