serversTransport:
  maxIdleConnsPerHost: 1000
  forwardingTimeouts:
    dialTimeout: 60
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https 
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 60
        graceTimeOut: 60
      respondingTimeouts:
        readTimeout: 120
        writeTimeout: 120
        idleTimeout: 240
  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 60
        graceTimeOut: 60
      respondingTimeouts:
        readTimeout: 120
        writeTimeout: 120
        idleTimeout: 240
  traefik:
    address: ":8080"
  mysql:
    address: ":3306"
api:
  insecure: true
  dashboard: true
  debug: false
certificatesResolvers:
  letsencrypt:
    acme:
      email: "master.gloqi@gmail.com"
      storage: "/acme/acme.json"
      httpChallenge:
        entryPoint: web
log:
  level: WARN
  filePath: "/etc/traefik/traefik.log"
  format: "json"
accessLog:
  filePath: "/etc/traefik/access.log"
  format: json
  fields:
    names:
      StartUTC: drop
  bufferingSize: 100
  filters:
    statusCodes:
      - "300-302"
      - "400-411"
      - "500-524"
providers:
  providersThrottleDuration: 2
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    swarmMode: false