serversTransport:
  maxIdleConnsPerHost: 1000
  forwardingTimeouts:
    dialTimeout: 120
entryPoints:
  http:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 120
        graceTimeOut: 120
      respondingTimeouts:
        readTimeout: 120
        writeTimeout: 120
        idleTimeout: 240
  https:
    address: ":443"
  mysql:
    address: ":3306"
api:
  insecure: true
  dashboard: true
  debug: false
log:
  level: ERROR
  filePath: "/etc/traefik/traefik.log"
  format: "json"
accessLog:
  filePath: "/etc/traefik/access.log"
  format: json
  fields:
    names:
      StartUTC: drop
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500"
providers:
  providersThrottleDuration: 2
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    swarmMode: false